/* Generated by Yosys 0.5+ (git sha1 f13e387, gcc 5.3.1-8ubuntu2 -O2 -fstack-protector-strong -fPIC -Os) */

(* src = "PHY.v:2" *)
module PCIE_PHY(CLK0, CLK1, CLK2, D, START_END, ORDERED_SET, LOG_COM, CONTROL, DATA_OUT, CONTROL_OUT, ERROR_DLL);
  (* src = "PHY.v:3" *)
  input CLK0;
  (* src = "PHY.v:4" *)
  input CLK1;
  (* src = "PHY.v:5" *)
  input CLK2;
  (* src = "PHY.v:12" *)
  input [1:0] CONTROL;
  (* src = "PHY.v:14" *)
  output [7:0] CONTROL_OUT;
  (* src = "PHY.v:7" *)
  input [7:0] D;
  (* src = "PHY.v:13" *)
  output [7:0] DATA_OUT;
  (* src = "PHY.v:15" *)
  output ERROR_DLL;
  (* src = "PHY.v:10" *)
  input [7:0] LOG_COM;
  (* src = "PHY.v:9" *)
  input [7:0] ORDERED_SET;
  (* src = "PHY.v:8" *)
  input [7:0] START_END;
  (* src = "PHY.v:17" *)
  wire [7:0] cable_d_out;
  (* src = "PHY.v:2" *)
  wire [7:0] \cable_datos[0] ;
  (* src = "PHY.v:2" *)
  wire [7:0] \cable_datos[1] ;
  (* src = "PHY.v:2" *)
  wire [7:0] \cable_datos[2] ;
  (* src = "PHY.v:2" *)
  wire [7:0] \cable_datos[3] ;
  (* src = "PHY.v:53" *)
  wire [3:0] cable_dk;
  (* src = "PHY.v:2" *)
  wire \cable_dk_o[0] ;
  (* src = "PHY.v:2" *)
  wire \cable_dk_o[1] ;
  (* src = "PHY.v:2" *)
  wire \cable_dk_o[2] ;
  (* src = "PHY.v:2" *)
  wire \cable_dk_o[3] ;
  (* src = "PHY.v:19" *)
  (* unused_bits = "0" *)
  wire cable_error;
  (* src = "PHY.v:2" *)
  wire [7:0] \cable_lane[0] ;
  (* src = "PHY.v:2" *)
  wire [7:0] \cable_lane[1] ;
  (* src = "PHY.v:2" *)
  wire [7:0] \cable_lane[2] ;
  (* src = "PHY.v:2" *)
  wire [7:0] \cable_lane[3] ;
  (* src = "PHY.v:18" *)
  wire cable_valid;
  (* src = "PHY.v:82" *)
  wire [7:0] o_D;
  (* src = "PHY.v:83" *)
  wire o_DK;
  (* src = "PHY.v:54" *)
  wire [3:0] temp_datos;
  (* src = "PHY.v:55" *)
  wire [3:0] temp_dk;
  (* src = "PHY.v:70" *)
  deserializador \$genblock$PHY.v:61$4057[0].phy_deserializador  (
    .DK(temp_dk[0]),
    .clk(CLK2),
    .data(temp_datos[0]),
    .out(\cable_datos[0] ),
    .out_DK(\cable_dk_o[0] )
  );
  (* src = "PHY.v:62" *)
  serializador \$genblock$PHY.v:61$4057[0].phy_serializador  (
    .DK(temp_dk[0]),
    .clk(CLK2),
    .data(\cable_lane[0] ),
    .enb(cable_dk[0]),
    .out(temp_datos[0])
  );
  (* src = "PHY.v:70" *)
  deserializador \$genblock$PHY.v:61$4058[1].phy_deserializador  (
    .DK(temp_dk[1]),
    .clk(CLK2),
    .data(temp_datos[1]),
    .out(\cable_datos[1] ),
    .out_DK(\cable_dk_o[1] )
  );
  (* src = "PHY.v:62" *)
  serializador \$genblock$PHY.v:61$4058[1].phy_serializador  (
    .DK(temp_dk[1]),
    .clk(CLK2),
    .data(\cable_lane[1] ),
    .enb(cable_dk[1]),
    .out(temp_datos[1])
  );
  (* src = "PHY.v:70" *)
  deserializador \$genblock$PHY.v:61$4059[2].phy_deserializador  (
    .DK(temp_dk[2]),
    .clk(CLK2),
    .data(temp_datos[2]),
    .out(\cable_datos[2] ),
    .out_DK(\cable_dk_o[2] )
  );
  (* src = "PHY.v:62" *)
  serializador \$genblock$PHY.v:61$4059[2].phy_serializador  (
    .DK(temp_dk[2]),
    .clk(CLK2),
    .data(\cable_lane[2] ),
    .enb(cable_dk[2]),
    .out(temp_datos[2])
  );
  (* src = "PHY.v:70" *)
  deserializador \$genblock$PHY.v:61$4060[3].phy_deserializador  (
    .DK(temp_dk[3]),
    .clk(CLK2),
    .data(temp_datos[3]),
    .out(\cable_datos[3] ),
    .out_DK(\cable_dk_o[3] )
  );
  (* src = "PHY.v:62" *)
  serializador \$genblock$PHY.v:61$4060[3].phy_serializador  (
    .DK(temp_dk[3]),
    .clk(CLK2),
    .data(\cable_lane[3] ),
    .enb(cable_dk[3]),
    .out(temp_datos[3])
  );
  (* src = "PHY.v:34" *)
  byte_strip phy_byte_strip (
    .CLK(CLK1),
    .D(cable_d_out),
    .DK(cable_valid),
    .DK_0(cable_dk[0]),
    .DK_1(cable_dk[1]),
    .DK_2(cable_dk[2]),
    .DK_3(cable_dk[3]),
    .ERROR_DLL(cable_error),
    .LANE0(\cable_lane[0] ),
    .LANE1(\cable_lane[1] ),
    .LANE2(\cable_lane[2] ),
    .LANE3(\cable_lane[3] )
  );
  (* src = "PHY.v:85" *)
  byte_unstrip phy_byte_unstrip (
    .CLK(CLK1),
    .D(o_D),
    .DK(o_DK),
    .DK_0(\cable_dk_o[0] ),
    .DK_1(\cable_dk_o[1] ),
    .DK_2(\cable_dk_o[2] ),
    .DK_3(\cable_dk_o[3] ),
    .LANE0(\cable_datos[0] ),
    .LANE1(\cable_datos[1] ),
    .LANE2(\cable_datos[2] ),
    .LANE3(\cable_datos[3] )
  );
  (* src = "PHY.v:101" *)
  demux phy_demux (
    .clk(CLK0),
    .control(CONTROL_OUT),
    .data_in(o_D),
    .data_out(DATA_OUT),
    .valid_in(o_DK)
  );
  (* src = "PHY.v:21" *)
  mux phy_mux (
    .D_in(D),
    .D_out(cable_d_out),
    .clk(CLK0),
    .control(CONTROL),
    .logical_COM(LOG_COM),
    .ordered_set(ORDERED_SET),
    .start_end(START_END),
    .valid(cable_valid)
  );
endmodule

(* src = "byte_striping/byte_striping.v:3" *)
module byte_strip(CLK, D, DK, LANE0, LANE1, LANE2, LANE3, DK_0, DK_1, DK_2, DK_3, ERROR_DLL);
  (* src = "byte_striping/byte_striping.v:5" *)
  input CLK;
  (* src = "byte_striping/byte_striping.v:6" *)
  input [7:0] D;
  (* src = "byte_striping/byte_striping.v:7" *)
  input DK;
  (* init = 1'bx *)
  (* src = "byte_striping/byte_striping.v:13" *)
  output DK_0;
  (* init = 1'bx *)
  (* src = "byte_striping/byte_striping.v:14" *)
  output DK_1;
  (* init = 1'bx *)
  (* src = "byte_striping/byte_striping.v:15" *)
  output DK_2;
  (* init = 1'bx *)
  (* src = "byte_striping/byte_striping.v:16" *)
  output DK_3;
  (* src = "byte_striping/byte_striping.v:17" *)
  output ERROR_DLL;
  (* src = "byte_striping/byte_striping.v:9" *)
  output [7:0] LANE0;
  (* src = "byte_striping/byte_striping.v:10" *)
  output [7:0] LANE1;
  (* src = "byte_striping/byte_striping.v:11" *)
  output [7:0] LANE2;
  (* src = "byte_striping/byte_striping.v:12" *)
  output [7:0] LANE3;
  assign DK_0 = 1'b0;
  assign DK_1 = 1'b0;
  assign DK_2 = 1'b0;
  assign DK_3 = 1'b0;
  assign ERROR_DLL = 1'b0;
  assign LANE0 = 8'bxxxxxxxx;
  assign LANE1 = 8'bxxxxxxxx;
  assign LANE2 = 8'bxxxxxxxx;
  assign LANE3 = 8'bxxxxxxxx;
endmodule

(* src = "byte_striping/byte_unstriping.v:3" *)
module byte_unstrip(CLK, LANE0, LANE1, LANE2, LANE3, DK_0, DK_1, DK_2, DK_3, D, DK);
  (* src = "byte_striping/byte_unstriping.v:5" *)
  input CLK;
  (* src = "byte_striping/byte_unstriping.v:15" *)
  output [7:0] D;
  (* src = "byte_striping/byte_unstriping.v:16" *)
  output DK;
  (* src = "byte_striping/byte_unstriping.v:10" *)
  input DK_0;
  (* src = "byte_striping/byte_unstriping.v:11" *)
  input DK_1;
  (* src = "byte_striping/byte_unstriping.v:12" *)
  input DK_2;
  (* src = "byte_striping/byte_unstriping.v:13" *)
  input DK_3;
  (* src = "byte_striping/byte_unstriping.v:6" *)
  input [7:0] LANE0;
  (* src = "byte_striping/byte_unstriping.v:7" *)
  input [7:0] LANE1;
  (* src = "byte_striping/byte_unstriping.v:8" *)
  input [7:0] LANE2;
  (* src = "byte_striping/byte_unstriping.v:9" *)
  input [7:0] LANE3;
  assign D = LANE3;
  assign DK = DK_3;
endmodule

(* src = "demux/demux.v:1" *)
module demux(valid_in, data_in, clk, data_out, control);
  (* src = "demux/demux.v:20" *)
  wire [7:0] _000_;
  (* src = "demux/demux.v:20" *)
  wire [7:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  (* src = "demux/demux.v:4" *)
  input clk;
  (* src = "demux/demux.v:6" *)
  output [7:0] control;
  (* src = "demux/demux.v:3" *)
  input [7:0] data_in;
  (* src = "demux/demux.v:5" *)
  output [7:0] data_out;
  (* src = "demux/demux.v:2" *)
  input valid_in;
  NOT _063_ (
    .A(data_in[0]),
    .Y(_002_)
  );
  NOT _064_ (
    .A(valid_in),
    .Y(_003_)
  );
  NOR _065_ (
    .A(_003_),
    .B(_002_),
    .Y(_001_[0])
  );
  NOT _066_ (
    .A(data_in[1]),
    .Y(_004_)
  );
  NOR _067_ (
    .A(_003_),
    .B(_004_),
    .Y(_001_[1])
  );
  NOT _068_ (
    .A(data_in[2]),
    .Y(_005_)
  );
  NOR _069_ (
    .A(_003_),
    .B(_005_),
    .Y(_001_[2])
  );
  NOT _070_ (
    .A(data_in[3]),
    .Y(_006_)
  );
  NOR _071_ (
    .A(_006_),
    .B(_003_),
    .Y(_001_[3])
  );
  NOT _072_ (
    .A(data_in[4]),
    .Y(_007_)
  );
  NOR _073_ (
    .A(_007_),
    .B(_003_),
    .Y(_001_[4])
  );
  NOT _074_ (
    .A(data_in[5]),
    .Y(_008_)
  );
  NOR _075_ (
    .A(_003_),
    .B(_008_),
    .Y(_001_[5])
  );
  NOT _076_ (
    .A(data_in[6]),
    .Y(_009_)
  );
  NOR _077_ (
    .A(_003_),
    .B(_009_),
    .Y(_001_[6])
  );
  NOT _078_ (
    .A(data_in[7]),
    .Y(_010_)
  );
  NOR _079_ (
    .A(_003_),
    .B(_010_),
    .Y(_001_[7])
  );
  NOR _080_ (
    .A(_007_),
    .B(_008_),
    .Y(_011_)
  );
  NOR _081_ (
    .A(_010_),
    .B(_009_),
    .Y(_012_)
  );
  NAND _082_ (
    .A(_012_),
    .B(_011_),
    .Y(_013_)
  );
  NOR _083_ (
    .A(_006_),
    .B(data_in[1]),
    .Y(_014_)
  );
  NOR _084_ (
    .A(_005_),
    .B(_002_),
    .Y(_015_)
  );
  NAND _085_ (
    .A(_015_),
    .B(_014_),
    .Y(_016_)
  );
  NOR _086_ (
    .A(_016_),
    .B(_013_),
    .Y(_017_)
  );
  NOR _087_ (
    .A(_006_),
    .B(_004_),
    .Y(_018_)
  );
  NOR _088_ (
    .A(data_in[2]),
    .B(_002_),
    .Y(_019_)
  );
  NAND _089_ (
    .A(_019_),
    .B(_018_),
    .Y(_020_)
  );
  NOR _090_ (
    .A(_020_),
    .B(_013_),
    .Y(_021_)
  );
  NOR _091_ (
    .A(_021_),
    .B(_017_),
    .Y(_022_)
  );
  NOR _092_ (
    .A(_022_),
    .B(valid_in),
    .Y(_000_[0])
  );
  NOR _093_ (
    .A(_005_),
    .B(data_in[0]),
    .Y(_023_)
  );
  NAND _094_ (
    .A(_023_),
    .B(_018_),
    .Y(_024_)
  );
  NOR _095_ (
    .A(_024_),
    .B(_013_),
    .Y(_025_)
  );
  NOR _096_ (
    .A(_025_),
    .B(_021_),
    .Y(_026_)
  );
  NOR _097_ (
    .A(_026_),
    .B(valid_in),
    .Y(_000_[1])
  );
  NAND _098_ (
    .A(_023_),
    .B(_014_),
    .Y(_027_)
  );
  NAND _099_ (
    .A(data_in[4]),
    .B(_008_),
    .Y(_028_)
  );
  NAND _100_ (
    .A(_010_),
    .B(_009_),
    .Y(_029_)
  );
  NOR _101_ (
    .A(_029_),
    .B(_028_),
    .Y(_030_)
  );
  NAND _102_ (
    .A(data_in[4]),
    .B(data_in[5]),
    .Y(_031_)
  );
  NOR _103_ (
    .A(_012_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _104_ (
    .A(_032_),
    .B(_030_),
    .Y(_033_)
  );
  NOR _105_ (
    .A(_033_),
    .B(_027_),
    .Y(_034_)
  );
  NAND _106_ (
    .A(data_in[7]),
    .B(data_in[6]),
    .Y(_035_)
  );
  NOR _107_ (
    .A(_035_),
    .B(_031_),
    .Y(_036_)
  );
  NAND _108_ (
    .A(data_in[3]),
    .B(_004_),
    .Y(_037_)
  );
  NAND _109_ (
    .A(data_in[2]),
    .B(data_in[0]),
    .Y(_038_)
  );
  NOR _110_ (
    .A(_038_),
    .B(_037_),
    .Y(_039_)
  );
  NAND _111_ (
    .A(_039_),
    .B(_036_),
    .Y(_040_)
  );
  NOR _112_ (
    .A(_007_),
    .B(data_in[5]),
    .Y(_041_)
  );
  NOR _113_ (
    .A(data_in[7]),
    .B(_009_),
    .Y(_042_)
  );
  NAND _114_ (
    .A(_042_),
    .B(_041_),
    .Y(_043_)
  );
  NOR _115_ (
    .A(_043_),
    .B(_027_),
    .Y(_044_)
  );
  NOR _116_ (
    .A(_044_),
    .B(_025_),
    .Y(_045_)
  );
  NAND _117_ (
    .A(_045_),
    .B(_040_),
    .Y(_046_)
  );
  NOR _118_ (
    .A(_046_),
    .B(_034_),
    .Y(_047_)
  );
  NOR _119_ (
    .A(_047_),
    .B(valid_in),
    .Y(_000_[2])
  );
  NAND _120_ (
    .A(_045_),
    .B(_022_),
    .Y(_048_)
  );
  NOR _121_ (
    .A(_048_),
    .B(_034_),
    .Y(_049_)
  );
  NOR _122_ (
    .A(_049_),
    .B(valid_in),
    .Y(_000_[4])
  );
  NAND _123_ (
    .A(data_in[2]),
    .B(_002_),
    .Y(_050_)
  );
  NOR _124_ (
    .A(_050_),
    .B(_037_),
    .Y(_051_)
  );
  NAND _125_ (
    .A(_051_),
    .B(_011_),
    .Y(_052_)
  );
  NOR _126_ (
    .A(_052_),
    .B(_012_),
    .Y(_053_)
  );
  NAND _127_ (
    .A(_026_),
    .B(_040_),
    .Y(_054_)
  );
  NOR _128_ (
    .A(_054_),
    .B(_053_),
    .Y(_055_)
  );
  NOR _129_ (
    .A(_055_),
    .B(valid_in),
    .Y(_000_[5])
  );
  NAND _130_ (
    .A(_010_),
    .B(data_in[6]),
    .Y(_056_)
  );
  NOR _131_ (
    .A(_056_),
    .B(_052_),
    .Y(_057_)
  );
  NOR _132_ (
    .A(_048_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _133_ (
    .A(_058_),
    .B(valid_in),
    .Y(_000_[6])
  );
  NAND _134_ (
    .A(data_in[7]),
    .B(_009_),
    .Y(_060_)
  );
  NOR _135_ (
    .A(_060_),
    .B(_052_),
    .Y(_061_)
  );
  NOR _136_ (
    .A(_054_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _137_ (
    .A(_062_),
    .B(valid_in),
    .Y(_000_[7])
  );
  NAND _138_ (
    .A(_049_),
    .B(_003_),
    .Y(_059_)
  );
  \$_DLATCH_P_  _139_ (
    .D(_001_[0]),
    .E(valid_in),
    .Q(data_out[0])
  );
  \$_DLATCH_P_  _140_ (
    .D(_001_[1]),
    .E(valid_in),
    .Q(data_out[1])
  );
  \$_DLATCH_P_  _141_ (
    .D(_001_[2]),
    .E(valid_in),
    .Q(data_out[2])
  );
  \$_DLATCH_P_  _142_ (
    .D(_001_[3]),
    .E(valid_in),
    .Q(data_out[3])
  );
  \$_DLATCH_P_  _143_ (
    .D(_001_[4]),
    .E(valid_in),
    .Q(data_out[4])
  );
  \$_DLATCH_P_  _144_ (
    .D(_001_[5]),
    .E(valid_in),
    .Q(data_out[5])
  );
  \$_DLATCH_P_  _145_ (
    .D(_001_[6]),
    .E(valid_in),
    .Q(data_out[6])
  );
  \$_DLATCH_P_  _146_ (
    .D(_001_[7]),
    .E(valid_in),
    .Q(data_out[7])
  );
  \$_DLATCH_P_  _147_ (
    .D(_000_[0]),
    .E(_059_),
    .Q(control[0])
  );
  \$_DLATCH_P_  _148_ (
    .D(_000_[1]),
    .E(_059_),
    .Q(control[1])
  );
  \$_DLATCH_P_  _149_ (
    .D(_000_[2]),
    .E(_059_),
    .Q(control[2])
  );
  \$_DLATCH_P_  _150_ (
    .D(_000_[4]),
    .E(_059_),
    .Q(control[4])
  );
  \$_DLATCH_P_  _151_ (
    .D(_000_[5]),
    .E(_059_),
    .Q(control[5])
  );
  \$_DLATCH_P_  _152_ (
    .D(_000_[6]),
    .E(_059_),
    .Q(control[6])
  );
  \$_DLATCH_P_  _153_ (
    .D(_000_[7]),
    .E(_059_),
    .Q(control[7])
  );
  assign control[3] = control[4];
endmodule

(* src = "serdes/Deserializador.v:5" *)
module deserializador(clk, data, DK, out_DK, out);
  (* src = "serdes/Deserializador.v:36" *)
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  (* src = "serdes/Deserializador.v:40" *)
  wire _34_;
  wire _35_;
  (* src = "serdes/Deserializador.v:10" *)
  input DK;
  (* src = "serdes/Deserializador.v:8" *)
  input clk;
  (* init = 4'b0111 *)
  (* src = "serdes/Deserializador.v:27" *)
  wire [3:0] counter;
  (* src = "serdes/Deserializador.v:9" *)
  input data;
  (* src = "serdes/Deserializador.v:13" *)
  output [7:0] out;
  (* src = "serdes/Deserializador.v:12" *)
  output out_DK;
  (* src = "serdes/Deserializador.v:28" *)
  wire [7:0] temp;
  NOT _36_ (
    .A(counter[3]),
    .Y(_08_)
  );
  NOT _37_ (
    .A(counter[2]),
    .Y(_09_)
  );
  NAND _38_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_10_)
  );
  NOR _39_ (
    .A(_10_),
    .B(_09_),
    .Y(_11_)
  );
  NOR _40_ (
    .A(_11_),
    .B(_08_),
    .Y(counter[3])
  );
  NAND _41_ (
    .A(_08_),
    .B(counter[2]),
    .Y(_12_)
  );
  NOR _42_ (
    .A(_12_),
    .B(_10_),
    .Y(_35_)
  );
  NOT _43_ (
    .A(counter[0]),
    .Y(counter[0])
  );
  NOT _44_ (
    .A(counter[1]),
    .Y(_13_)
  );
  NAND _45_ (
    .A(_13_),
    .B(counter[0]),
    .Y(_14_)
  );
  NAND _46_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_15_)
  );
  NAND _47_ (
    .A(_15_),
    .B(_14_),
    .Y(counter[1])
  );
  NOR _48_ (
    .A(_13_),
    .B(counter[0]),
    .Y(_16_)
  );
  NOR _49_ (
    .A(_16_),
    .B(counter[2]),
    .Y(_17_)
  );
  NOR _50_ (
    .A(_17_),
    .B(_11_),
    .Y(counter[2])
  );
  NOR _51_ (
    .A(counter[3]),
    .B(counter[2]),
    .Y(_18_)
  );
  NOR _52_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_19_)
  );
  NAND _53_ (
    .A(_19_),
    .B(_18_),
    .Y(_20_)
  );
  NOT _54_ (
    .A(_20_),
    .Y(_34_)
  );
  NOT _55_ (
    .A(data),
    .Y(_21_)
  );
  NOR _56_ (
    .A(_20_),
    .B(_21_),
    .Y(_00_[7])
  );
  NOR _57_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_22_)
  );
  NAND _58_ (
    .A(_18_),
    .B(_22_),
    .Y(_23_)
  );
  NOR _59_ (
    .A(_23_),
    .B(_21_),
    .Y(_00_[6])
  );
  NOR _60_ (
    .A(_13_),
    .B(counter[0]),
    .Y(_24_)
  );
  NAND _61_ (
    .A(_18_),
    .B(_24_),
    .Y(_25_)
  );
  NOR _62_ (
    .A(_25_),
    .B(_21_),
    .Y(_00_[5])
  );
  NAND _63_ (
    .A(_18_),
    .B(_16_),
    .Y(_26_)
  );
  NOR _64_ (
    .A(_26_),
    .B(_21_),
    .Y(_00_[4])
  );
  NOR _65_ (
    .A(counter[3]),
    .B(_09_),
    .Y(_27_)
  );
  NAND _66_ (
    .A(_19_),
    .B(_27_),
    .Y(_28_)
  );
  NOR _67_ (
    .A(_28_),
    .B(_21_),
    .Y(_00_[3])
  );
  NAND _68_ (
    .A(_22_),
    .B(_27_),
    .Y(_29_)
  );
  NOR _69_ (
    .A(_29_),
    .B(_21_),
    .Y(_00_[2])
  );
  NAND _70_ (
    .A(_24_),
    .B(_27_),
    .Y(_30_)
  );
  NOR _71_ (
    .A(_30_),
    .B(_21_),
    .Y(_00_[1])
  );
  NAND _72_ (
    .A(_11_),
    .B(_08_),
    .Y(_31_)
  );
  NOR _73_ (
    .A(_31_),
    .B(_21_),
    .Y(_00_[0])
  );
  NOR _74_ (
    .A(_15_),
    .B(_12_),
    .Y(_01_)
  );
  NOR _75_ (
    .A(_14_),
    .B(_12_),
    .Y(_02_)
  );
  NOT _76_ (
    .A(_19_),
    .Y(_32_)
  );
  NOR _77_ (
    .A(_32_),
    .B(_12_),
    .Y(_03_)
  );
  NOT _78_ (
    .A(_18_),
    .Y(_33_)
  );
  NOR _79_ (
    .A(_33_),
    .B(_10_),
    .Y(_04_)
  );
  NOR _80_ (
    .A(_33_),
    .B(_15_),
    .Y(_05_)
  );
  NOR _81_ (
    .A(_33_),
    .B(_14_),
    .Y(_06_)
  );
  BUF _82_ (
    .A(_34_),
    .Y(_07_)
  );
  DFF _83_ (
    .C(_34_),
    .D(temp[0]),
    .Q(out[0])
  );
  DFF _84_ (
    .C(_34_),
    .D(temp[1]),
    .Q(out[1])
  );
  DFF _85_ (
    .C(_34_),
    .D(temp[2]),
    .Q(out[2])
  );
  DFF _86_ (
    .C(_34_),
    .D(temp[3]),
    .Q(out[3])
  );
  DFF _87_ (
    .C(_34_),
    .D(temp[4]),
    .Q(out[4])
  );
  DFF _88_ (
    .C(_34_),
    .D(temp[5]),
    .Q(out[5])
  );
  DFF _89_ (
    .C(_34_),
    .D(temp[6]),
    .Q(out[6])
  );
  DFF _90_ (
    .C(_34_),
    .D(temp[7]),
    .Q(out[7])
  );
  DFF _91_ (
    .C(_34_),
    .D(DK),
    .Q(out_DK)
  );
  \$_DLATCH_P_  _92_ (
    .D(_00_[0]),
    .E(_35_),
    .Q(temp[0])
  );
  \$_DLATCH_P_  _93_ (
    .D(_00_[1]),
    .E(_01_),
    .Q(temp[1])
  );
  \$_DLATCH_P_  _94_ (
    .D(_00_[2]),
    .E(_02_),
    .Q(temp[2])
  );
  \$_DLATCH_P_  _95_ (
    .D(_00_[3]),
    .E(_03_),
    .Q(temp[3])
  );
  \$_DLATCH_P_  _96_ (
    .D(_00_[4]),
    .E(_04_),
    .Q(temp[4])
  );
  \$_DLATCH_P_  _97_ (
    .D(_00_[5]),
    .E(_05_),
    .Q(temp[5])
  );
  \$_DLATCH_P_  _98_ (
    .D(_00_[6]),
    .E(_06_),
    .Q(temp[6])
  );
  \$_DLATCH_P_  _99_ (
    .D(_00_[7]),
    .E(_07_),
    .Q(temp[7])
  );
endmodule

(* src = "mux/mux.v:1" *)
module mux(clk, control, D_in, start_end, ordered_set, logical_COM, D_out, valid);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  (* src = "mux/mux.v:5" *)
  input [7:0] D_in;
  (* src = "mux/mux.v:10" *)
  output [7:0] D_out;
  (* src = "mux/mux.v:2" *)
  input clk;
  (* src = "mux/mux.v:3" *)
  input [1:0] control;
  (* src = "mux/mux.v:8" *)
  input [7:0] logical_COM;
  (* src = "mux/mux.v:7" *)
  input [7:0] ordered_set;
  (* src = "mux/mux.v:6" *)
  input [7:0] start_end;
  (* src = "mux/mux.v:11" *)
  output valid;
  NOR _060_ (
    .A(control[1]),
    .B(control[0]),
    .Y(valid)
  );
  NOT _061_ (
    .A(control[0]),
    .Y(_011_)
  );
  NOR _062_ (
    .A(control[1]),
    .B(_011_),
    .Y(_012_)
  );
  NOR _063_ (
    .A(_012_),
    .B(_011_),
    .Y(_013_)
  );
  NAND _064_ (
    .A(_013_),
    .B(logical_COM[0]),
    .Y(_014_)
  );
  NOT _065_ (
    .A(ordered_set[0]),
    .Y(_015_)
  );
  NAND _066_ (
    .A(control[1]),
    .B(_011_),
    .Y(_016_)
  );
  NOR _067_ (
    .A(_016_),
    .B(_015_),
    .Y(_017_)
  );
  NAND _068_ (
    .A(_012_),
    .B(start_end[0]),
    .Y(_018_)
  );
  NAND _069_ (
    .A(valid),
    .B(D_in[0]),
    .Y(_019_)
  );
  NAND _070_ (
    .A(_019_),
    .B(_018_),
    .Y(_020_)
  );
  NOR _071_ (
    .A(_020_),
    .B(_017_),
    .Y(_021_)
  );
  NAND _072_ (
    .A(_021_),
    .B(_014_),
    .Y(D_out[0])
  );
  NAND _073_ (
    .A(_013_),
    .B(logical_COM[1]),
    .Y(_022_)
  );
  NOT _074_ (
    .A(ordered_set[1]),
    .Y(_023_)
  );
  NOR _075_ (
    .A(_016_),
    .B(_023_),
    .Y(_024_)
  );
  NAND _076_ (
    .A(_012_),
    .B(start_end[1]),
    .Y(_025_)
  );
  NAND _077_ (
    .A(valid),
    .B(D_in[1]),
    .Y(_026_)
  );
  NAND _078_ (
    .A(_026_),
    .B(_025_),
    .Y(_027_)
  );
  NOR _079_ (
    .A(_027_),
    .B(_024_),
    .Y(_028_)
  );
  NAND _080_ (
    .A(_028_),
    .B(_022_),
    .Y(D_out[1])
  );
  NAND _081_ (
    .A(_013_),
    .B(logical_COM[2]),
    .Y(_029_)
  );
  NOT _082_ (
    .A(ordered_set[2]),
    .Y(_030_)
  );
  NOR _083_ (
    .A(_016_),
    .B(_030_),
    .Y(_031_)
  );
  NAND _084_ (
    .A(_012_),
    .B(start_end[2]),
    .Y(_032_)
  );
  NAND _085_ (
    .A(valid),
    .B(D_in[2]),
    .Y(_033_)
  );
  NAND _086_ (
    .A(_033_),
    .B(_032_),
    .Y(_034_)
  );
  NOR _087_ (
    .A(_034_),
    .B(_031_),
    .Y(_035_)
  );
  NAND _088_ (
    .A(_035_),
    .B(_029_),
    .Y(D_out[2])
  );
  NAND _089_ (
    .A(_013_),
    .B(logical_COM[3]),
    .Y(_036_)
  );
  NOT _090_ (
    .A(ordered_set[3]),
    .Y(_037_)
  );
  NOR _091_ (
    .A(_016_),
    .B(_037_),
    .Y(_038_)
  );
  NAND _092_ (
    .A(_012_),
    .B(start_end[3]),
    .Y(_039_)
  );
  NAND _093_ (
    .A(valid),
    .B(D_in[3]),
    .Y(_040_)
  );
  NAND _094_ (
    .A(_040_),
    .B(_039_),
    .Y(_041_)
  );
  NOR _095_ (
    .A(_041_),
    .B(_038_),
    .Y(_042_)
  );
  NAND _096_ (
    .A(_042_),
    .B(_036_),
    .Y(D_out[3])
  );
  NAND _097_ (
    .A(_013_),
    .B(logical_COM[4]),
    .Y(_043_)
  );
  NOT _098_ (
    .A(ordered_set[4]),
    .Y(_044_)
  );
  NOR _099_ (
    .A(_016_),
    .B(_044_),
    .Y(_045_)
  );
  NAND _100_ (
    .A(_012_),
    .B(start_end[4]),
    .Y(_046_)
  );
  NAND _101_ (
    .A(valid),
    .B(D_in[4]),
    .Y(_047_)
  );
  NAND _102_ (
    .A(_047_),
    .B(_046_),
    .Y(_048_)
  );
  NOR _103_ (
    .A(_048_),
    .B(_045_),
    .Y(_049_)
  );
  NAND _104_ (
    .A(_049_),
    .B(_043_),
    .Y(D_out[4])
  );
  NAND _105_ (
    .A(_013_),
    .B(logical_COM[5]),
    .Y(_050_)
  );
  NOT _106_ (
    .A(ordered_set[5]),
    .Y(_051_)
  );
  NOR _107_ (
    .A(_016_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _108_ (
    .A(_012_),
    .B(start_end[5]),
    .Y(_053_)
  );
  NAND _109_ (
    .A(valid),
    .B(D_in[5]),
    .Y(_054_)
  );
  NAND _110_ (
    .A(_054_),
    .B(_053_),
    .Y(_055_)
  );
  NOR _111_ (
    .A(_055_),
    .B(_052_),
    .Y(_056_)
  );
  NAND _112_ (
    .A(_056_),
    .B(_050_),
    .Y(D_out[5])
  );
  NAND _113_ (
    .A(_013_),
    .B(logical_COM[6]),
    .Y(_057_)
  );
  NOT _114_ (
    .A(ordered_set[6]),
    .Y(_058_)
  );
  NOR _115_ (
    .A(_016_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _116_ (
    .A(_012_),
    .B(start_end[6]),
    .Y(_000_)
  );
  NAND _117_ (
    .A(valid),
    .B(D_in[6]),
    .Y(_001_)
  );
  NAND _118_ (
    .A(_001_),
    .B(_000_),
    .Y(_002_)
  );
  NOR _119_ (
    .A(_002_),
    .B(_059_),
    .Y(_003_)
  );
  NAND _120_ (
    .A(_003_),
    .B(_057_),
    .Y(D_out[6])
  );
  NAND _121_ (
    .A(_013_),
    .B(logical_COM[7]),
    .Y(_004_)
  );
  NOT _122_ (
    .A(ordered_set[7]),
    .Y(_005_)
  );
  NOR _123_ (
    .A(_016_),
    .B(_005_),
    .Y(_006_)
  );
  NAND _124_ (
    .A(_012_),
    .B(start_end[7]),
    .Y(_007_)
  );
  NAND _125_ (
    .A(valid),
    .B(D_in[7]),
    .Y(_008_)
  );
  NAND _126_ (
    .A(_008_),
    .B(_007_),
    .Y(_009_)
  );
  NOR _127_ (
    .A(_009_),
    .B(_006_),
    .Y(_010_)
  );
  NAND _128_ (
    .A(_010_),
    .B(_004_),
    .Y(D_out[7])
  );
endmodule

(* src = "serdes/SerializadorUv.v:5" *)
module serializador(enb, data, clk, DK, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  (* src = "serdes/SerializadorUv.v:12" *)
  output DK;
  (* src = "serdes/SerializadorUv.v:8" *)
  input clk;
  (* init = 4'b0111 *)
  (* src = "serdes/SerializadorUv.v:15" *)
  wire [3:0] counter;
  (* src = "serdes/SerializadorUv.v:9" *)
  input [7:0] data;
  (* src = "serdes/SerializadorUv.v:8" *)
  input enb;
  (* src = "serdes/SerializadorUv.v:11" *)
  output out;
  NOT _33_ (
    .A(counter[3]),
    .Y(_00_)
  );
  NOT _34_ (
    .A(counter[2]),
    .Y(_01_)
  );
  NAND _35_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_02_)
  );
  NOR _36_ (
    .A(_02_),
    .B(_01_),
    .Y(_03_)
  );
  NOR _37_ (
    .A(_03_),
    .B(_00_),
    .Y(counter[3])
  );
  NOT _38_ (
    .A(counter[0]),
    .Y(counter[0])
  );
  NOT _39_ (
    .A(_02_),
    .Y(_04_)
  );
  NOR _40_ (
    .A(counter[1]),
    .B(counter[0]),
    .Y(_05_)
  );
  NOR _41_ (
    .A(_05_),
    .B(_04_),
    .Y(counter[1])
  );
  NOR _42_ (
    .A(_04_),
    .B(counter[2]),
    .Y(_06_)
  );
  NOR _43_ (
    .A(_06_),
    .B(_03_),
    .Y(counter[2])
  );
  NOT _44_ (
    .A(data[7]),
    .Y(_07_)
  );
  NAND _45_ (
    .A(_01_),
    .B(_07_),
    .Y(_08_)
  );
  NOR _46_ (
    .A(_01_),
    .B(data[3]),
    .Y(_09_)
  );
  NOR _47_ (
    .A(_09_),
    .B(counter[1]),
    .Y(_10_)
  );
  NAND _48_ (
    .A(_10_),
    .B(_08_),
    .Y(_11_)
  );
  NOT _49_ (
    .A(data[1]),
    .Y(_12_)
  );
  NAND _50_ (
    .A(counter[2]),
    .B(_12_),
    .Y(_13_)
  );
  NOT _51_ (
    .A(counter[1]),
    .Y(_14_)
  );
  NOR _52_ (
    .A(counter[2]),
    .B(data[5]),
    .Y(_15_)
  );
  NOR _53_ (
    .A(_15_),
    .B(_14_),
    .Y(_16_)
  );
  NAND _54_ (
    .A(_16_),
    .B(_13_),
    .Y(_17_)
  );
  NAND _55_ (
    .A(_17_),
    .B(_11_),
    .Y(_18_)
  );
  NOR _56_ (
    .A(_18_),
    .B(counter[0]),
    .Y(_19_)
  );
  NOR _57_ (
    .A(counter[2]),
    .B(data[6]),
    .Y(_20_)
  );
  NOT _58_ (
    .A(data[2]),
    .Y(_21_)
  );
  NAND _59_ (
    .A(counter[2]),
    .B(_21_),
    .Y(_22_)
  );
  NAND _60_ (
    .A(_22_),
    .B(_14_),
    .Y(_23_)
  );
  NOR _61_ (
    .A(_23_),
    .B(_20_),
    .Y(_24_)
  );
  NOR _62_ (
    .A(_01_),
    .B(data[0]),
    .Y(_25_)
  );
  NOT _63_ (
    .A(data[4]),
    .Y(_26_)
  );
  NAND _64_ (
    .A(_01_),
    .B(_26_),
    .Y(_27_)
  );
  NAND _65_ (
    .A(_27_),
    .B(counter[1]),
    .Y(_28_)
  );
  NOR _66_ (
    .A(_28_),
    .B(_25_),
    .Y(_29_)
  );
  NOR _67_ (
    .A(_29_),
    .B(_24_),
    .Y(_30_)
  );
  NAND _68_ (
    .A(_30_),
    .B(counter[0]),
    .Y(_31_)
  );
  NAND _69_ (
    .A(_31_),
    .B(_00_),
    .Y(_32_)
  );
  NOR _70_ (
    .A(_32_),
    .B(_19_),
    .Y(out)
  );
  assign DK = enb;
endmodule
